### ISSUE TITLE
[Refactor] Upgrade Clickhouse server to 22.8

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1087]
As discussed in https://github.com/X-lab2017/open-wonderland/issues/222 , we will upgrade our Clickhouse cloud service server version from 20.8 to 22.8 recently. The data upload progress will be completed in 2 days.

Then we need to upgrade OpenDigger kernel to make sure OpenDigger is compatible with the server version.

The js kernel need to change underlying Clickhouse client library from [`@apla/clickhouse`](https://www.npmjs.com/package/@apla/clickhouse) to [`@clickhouse/client`](https://www.npmjs.com/package/@clickhouse/client) which is the official js client for Clickhouse and support 22.8 as the minimal version.

For client upgrade, we also need to upgrade Clickhouse sample data server image to 22.8 to make sure it is compatible with OpenDigger.

So the things we need to do includes:

- [x] Upgrade js kernel underlying library. #1098 
- [x] Upgrade python kernel underlying library. #1113 
- [x] Upgrade Clickhouse sample data server image version. #1099 

When all above tasks finished, we can entirely transform from Clickhouse 20.8 to 22.8 with more great features created by Clickhouse in past 2 years.
