### ISSUE TITLE
[OSPP] Task - Implement CHAOSS Metrics

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#878]
There are 16 CHAOSS metrics related to **Project Evolution**. During OSPP, we wish to implement some of them.

## Code Development Activity
- [x] [Code Changes Commits](https://chaoss.community/metric-code-changes-commits/) #578
- [x] [Code Changes Lines](https://chaoss.community/metric-code-changes-lines/) #579

## Code Development Efficiency
- [x] [Change Requests Accepted](https://chaoss.community/metric-change-requests-accepted/) #581
- [x] [Change Requests Declined](https://chaoss.community/metric-change-requests-declined/) #582
- [x] [Change Request Duration](https://chaoss.community/metric-change-requests-duration/) #583
- [x] [Change Request Acceptance Ratio](https://chaoss.community/metric-change-request-acceptance-ratio/) #584

## Issue Resolution
- [x] [Issues New](https://chaoss.community/metric-issues-new/) #585 
- [x] [Issues Closed](https://chaoss.community/metric-issues-closed/) #587 
- [x] [Issue Age](https://chaoss.community/metric-issue-age/) #588
- [x] [Issues Active](https://chaoss.community/metric-issues-active/) #586 
- [x] [Issue Response Time](https://chaoss.community/metric-issue-response-time/) #589 
- [x] [Issue Resolution Duration](https://chaoss.community/metric-issue-resolution-duration/) #590 

## Community Growth
- [ ] [Contribution Attribution](https://chaoss.community/metric-contribution-attribution/) -  we don't have an issue yet, but this can be implemented using email suffix.
- [x] [New Contributors](https://chaoss.community/metric-new-contributors/) #592
- [x] [Inactive Contributors](https://chaoss.community/metric-inactive-contributors/) #591
- [x] [New Contributors Closing Issues](https://chaoss.community/metric-new-contributors-closing-issues/) #593

**Comment by xiaoya-yaya** [comment]
#### Bus Factor is a metric related to Risk, but its important to observe a project's decline:
- [ ] [Bus Factor](https://chaoss.community/metric-bus-factor/) #594 

Refer to a tentative [metric model](https://docs.google.com/document/d/1FhNeYFVETfetSGq4wJ4xJJvsqMe6p_NBs9KgQFSAQGE/edit) for more.

**Comment by xiaoya-yaya** [comment]
Please comment `/self-assign` under corresponding metric issues that you plan to implement, thus other people won't duplicate the implementation. @longyanz

**Comment by frank-zsy** [comment]
The `contributor attribution` metric is implemented as `contributor email suffixes` metric in #1159 , close this issue for now, if we have more data in the future, we can open new issues to implement this metric. @xiaoya-yaya

**Comment by xgdyp** [comment]
That‘s awesome！
